build: update base image for Emscripten in Dockerfile

diff --git a/src/platforms/wasm/compiler/Dockerfile b/src/platforms/wasm/compiler/Dockerfile
--- a/src/platforms/wasm/compiler/Dockerfile
+++ b/src/platforms/wasm/compiler/Dockerfile
@@ -1,14 +1,12 @@
-FROM trzeci/emscripten:1.39.17-upstream AS emscripten_base
-# A good practice is to don't use `latest` - even if some effort is made to make sure that `latest` version is stable
+FROM emscripten/emsdk:3.1.70 AS emscripten_base
 
 # Target base image
 FROM fedora
 
 # Copy pre-compiled content of Emscripten SDK to target image
-COPY --from=emscripten_base /emsdk_portable /emsdk_portable
+COPY --from=emscripten_base /emsdk /emsdk
 
 # Install required tools to run Emscripten SDK
-
 RUN echo "max_parallel_downloads=10" >> /etc/dnf/dnf.conf
 
 RUN dnf install -y git nano which ca-certificates python3 python3-pip dos2unix tar wget unzip make cmake ninja-build && \
@@ -28,7 +26,7 @@ RUN mkdir -p /container/bin && \
     ln -s /usr/bin/pip3 /container/bin/pip
 
 # Add Python and Emscripten to PATH
-ENV PATH="/container/bin:/usr/local/bin:/usr/bin:/emsdk_portable:/emsdk_portable/upstream/emscripten:${PATH}"
+ENV PATH="/container/bin:/usr/local/bin:/usr/bin:/emsdk:/emsdk/upstream/emscripten:${PATH}"
 
 # Create a custom print script
 RUN echo '#!/bin/sh' > /usr/bin/print && \
@@ -38,23 +36,19 @@ RUN echo '#!/bin/sh' > /usr/bin/print && \
 # Add print function and PATH modifications to /etc/profile
 RUN echo 'print() { echo "$@"; }' >> /etc/profile && \
     echo 'export -f print' >> /etc/profile && \
-    echo 'export PATH="/container/bin:/usr/bin:/emsdk_portable:/emsdk_portable/upstream/emscripten:$PATH"' >> /etc/profile && \
-    echo 'source /emsdk_portable/emsdk_env.sh' >> /etc/profile
+    echo 'export PATH="/container/bin:/usr/bin:/emsdk:/emsdk/upstream/emscripten:$PATH"' >> /etc/profile && \
+    echo 'source /emsdk/emsdk_env.sh' >> /etc/profile
 
-# wormhole-tx allows to send/recieve files to the host machine. The command `tx` becomes available.
-RUN pip3 install wormhole-tx || true
-
-# src\platforms\stub\wasm\compiler\install-arduino-cli.sh
-
-COPY src/platforms/wasm/compiler/install-arduino-cli.sh /install-arduino-cli.sh
-RUN chmod +x /install-arduino-cli.sh && /install-arduino-cli.sh || echo "Failed to install Arduino CLI"
-
+#COPY src/platforms/wasm/compiler/install-arduino-cli.sh /install-arduino-cli.sh
+#RUN chmod +x /install-arduino-cli.sh && /install-arduino-cli.sh || echo "Failed to install Arduino CLI"
+    
 
 # Set up the entrypoint script
 RUN echo '#!/bin/bash' > /entrypoint.sh && \
-    echo 'source /emsdk_portable/emsdk_env.sh' >> /entrypoint.sh && \
+    echo 'source /emsdk/emsdk_env.sh' >> /entrypoint.sh && \
     echo 'exec "$@"' >> /entrypoint.sh && \
     chmod +x /entrypoint.sh
+
 
 # In order to speed up the build, copy files that are not likely
 # to be changed first.
@@ -95,8 +89,8 @@ WORKDIR /js
 
 # This is too slow for lots of testing, disabled for now
 # Prewarm the cache with a first compile.
-RUN mkdir -p /js/src && echo -e "void setup() {}\nvoid loop(){}\n" > /js/src/prewarm_main.cpp
-RUN source /entrypoint.sh && pio run && rm -rf /js/src/prewarm_main.cpp
+#RUN mkdir -p /js/src && echo -e "void setup() {}\nvoid loop(){}\n" > /js/src/prewarm_main.cpp
+#RUN source /entrypoint.sh && pio run && rm -rf /js/src/prewarm_main.cpp
 
 # Copy the compile script
 COPY src/platforms/wasm/compiler/compile.py /js/
