feat: add 'All White' checkbox functionality for LED control

diff --git a/src/platforms/wasm/compiler/Dockerfile b/src/platforms/wasm/compiler/Dockerfile
--- a/src/platforms/wasm/compiler/Dockerfile
+++ b/src/platforms/wasm/compiler/Dockerfile
@@ -77,18 +77,6 @@ RUN cp /js/fastled/src/platforms/wasm/compiler/platformio.ini /js/platformio.ini
     cp /js/fastled/src/platforms/wasm/compiler/arduino-pre-process.sh /js/arduino-pre-process.sh && \
     cp /js/fastled/src/platforms/wasm/compiler/*.sh /js/
 
-# Build with --build-arg DEBUG=1 to enable debug mode
-ARG DEBUG=0
-ENV DEBUG=${DEBUG}
-# now set it in /etc/profile, if it exists
-RUN if \
-    [ -f /etc/profile ] && \
-    [ "${DEBUG}" = "1" ]; then \
-    echo 'export DEBUG=1' >> /etc/profile; \
-    echo 'echo "Debug mode enabled"' >> /etc/profile; \
-    fi
-
-
 WORKDIR /js
 
 # This is too slow for lots of testing, disabled for now
@@ -105,7 +93,7 @@ RUN dos2unix /js/compile.py /js/process-ino.py
 RUN dos2unix /js/*.sh
 RUN chmod +x /js/*.sh
 
-RUN python /js/compile.py
+RUN python /js/compile.py || echo "####### ERROR FAILED to run pre warm compiler toolchain. Compile performance will degrade with this docker image."
 
 #Clean up before the volume get's mapped in.
 RUN rm -rf /mapped
